# Generated by Django 5.2.16 on 2026-07-11 21:09

import django.db.models.deletion
import tournaments.constants
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('entry_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji glyph', max_length=8)),
                ('color_token', models.CharField(blank=True, help_text='CSS token, e.g. sport-basketball', max_length=40)),
                ('format_type', models.CharField(default='TEAM', max_length=12)),
                ('default_format', models.CharField(choices=[('KNOCKOUT', 'Single-elimination bracket'), ('ROUND_ROBIN', 'Round-robin points table'), ('TIME_TRIAL', 'Time-trial / leaderboard'), ('SINGLE_EVENT', 'Single-event ranking')], default='KNOCKOUT', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round_name', models.CharField(blank=True, max_length=60)),
                ('round_no', models.PositiveIntegerField(default=1)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('bracket_position', models.PositiveIntegerField(blank=True, null=True)),
                ('session_no', models.PositiveIntegerField(default=1, help_text='Time-trial: qualifying=1, race=2, ...')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('venue_detail', models.CharField(blank=True, help_text='Court / lane / table', max_length=120)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=12)),
                ('youtube_url', models.URLField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('result_published', models.BooleanField(default=True)),
                ('advances_slot', models.PositiveIntegerField(blank=True, null=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('advances_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeders', to='tournaments.fixture')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.eventcategory')),
            ],
            options={
                'ordering': ['round_no', 'sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FixtureParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Fallback name for account-less entrants', max_length=120)),
                ('slot', models.PositiveIntegerField(default=0, help_text='0/1 for head-to-head; 0..n otherwise')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('is_winner', models.BooleanField(blank=True, null=True)),
                ('result_state', models.CharField(choices=[('OK', 'Finished'), ('DNF', 'Did not finish'), ('DSQ', 'Disqualified')], default='OK', max_length=3)),
                ('time_ms', models.PositiveIntegerField(blank=True, help_text='Finish time in ms for time formats', null=True)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournaments.fixture')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.playerprofile')),
            ],
            options={
                'ordering': ['slot', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScoreEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(default='note', max_length=30)),
                ('description', models.CharField(max_length=280)),
                ('score_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tournaments.fixture')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.fixtureparticipant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/')),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captained_teams', to='accounts.playerprofile')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournaments.sport')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fixtureparticipant',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.team'),
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text='For roster entries without a platform account', max_length=120)),
                ('role', models.CharField(choices=[('CAPTAIN', 'Captain'), ('MEMBER', 'Member')], default='MEMBER', max_length=10)),
                ('jersey_number', models.CharField(blank=True, max_length=8)),
                ('is_approved', models.BooleanField(default=True, help_text='False = pending player join request')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='accounts.playerprofile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tournaments.team')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('format', models.CharField(choices=[('KNOCKOUT', 'Single-elimination bracket'), ('ROUND_ROBIN', 'Round-robin points table'), ('TIME_TRIAL', 'Time-trial / leaderboard'), ('SINGLE_EVENT', 'Single-event ranking')], max_length=20)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='tournaments/')),
                ('entry_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Upcoming'), ('ONGOING', 'Live'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=12)),
                ('is_featured', models.BooleanField(default=False)),
                ('featured_order', models.PositiveIntegerField(default=0)),
                ('youtube_url', models.URLField(blank=True, help_text='Default stream for the whole tournament')),
                ('points_config', models.JSONField(blank=True, default=tournaments.constants.default_points_config)),
                ('fixtures_generated', models.BooleanField(default=False)),
                ('is_removed', models.BooleanField(default=False)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='accounts.organizerprofile')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='tournaments.sport')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.venue')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=40)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('played', models.PositiveIntegerField(default=0)),
                ('won', models.PositiveIntegerField(default=0)),
                ('lost', models.PositiveIntegerField(default=0)),
                ('drawn', models.PositiveIntegerField(default=0)),
                ('points', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('position', models.PositiveIntegerField(default=0)),
                ('extra_stats', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.playerprofile')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['position', '-points'],
            },
        ),
        migrations.CreateModel(
            name='IndividualRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text='For entrants added by the organizer without an account', max_length=120)),
                ('bib_number', models.CharField(blank=True, max_length=12)),
                ('seed', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=10)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.eventcategory')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='accounts.playerprofile')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['seed', 'registered_at'],
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, max_length=800)),
                ('image', models.ImageField(blank=True, null=True, upload_to='highlights/')),
                ('youtube_url', models.URLField(blank=True)),
                ('best_performer', models.CharField(blank=True, max_length=120)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fixture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='tournaments.fixture')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='fixture',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tournaments.tournament'),
        ),
        migrations.CreateModel(
            name='TournamentTeamEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=10)),
                ('seed', models.PositiveIntegerField(blank=True, null=True)),
                ('group_name', models.CharField(blank=True, max_length=40)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tournaments.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_entries', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['seed', 'registered_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='fixtureparticipant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('player__isnull', True), ('team__isnull', False)), models.Q(('player__isnull', False), ('team__isnull', True)), models.Q(('player__isnull', True), ('team__isnull', True)), _connector='OR'), name='fixtureparticipant_exactly_one_competitor'),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(condition=models.Q(('player__isnull', False)), fields=('team', 'player'), name='uniq_team_player'),
        ),
        migrations.AddConstraint(
            model_name='individualregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('player__isnull', False)), fields=('tournament', 'player'), name='uniq_tournament_player'),
        ),
        migrations.AddConstraint(
            model_name='tournamentteamentry',
            constraint=models.UniqueConstraint(fields=('tournament', 'team'), name='uniq_tournament_team'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['status', 'is_featured'], name='tournaments_status_793c82_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['sport', 'status'], name='tournaments_sport_i_9a6c17_idx'),
        ),
    ]
