# Generated by Django 5.2.16 on 2026-07-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventcategory",
            name="distance_km",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Distance in km (5, 10, 21.1, 42.2…). Enables pace on the leaderboard.",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="highlight",
            name="duration_seconds",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Runtime of the clip, shown as a badge on the thumbnail.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="highlight",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tournament",
            name="prize_pool",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total prize money, shown on the tournament card.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="rules",
            field=models.TextField(
                blank=True,
                help_text="Format, tie-breaks, time control — shown on the tournament page.",
            ),
        ),
    ]
