# Generated by Django 5.2.16 on 2026-07-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_eventcategory_distance_km_highlight_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='extra_time_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fixture',
            name='live_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
