# Generated by Django 5.2.16 on 2026-07-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_fixture_extra_time_seconds_fixture_live_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='clock_paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='current_period',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fixtureparticipant',
            name='fouls',
            field=models.PositiveSmallIntegerField(default=0, help_text='Team foul count (basketball only)'),
        ),
    ]
