# Generated by Django 5.2.16 on 2026-07-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_fixture_clock_paused_at_fixture_current_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='quarter_length_seconds',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AddField(
            model_name='fixture',
            name='shot_clock_running_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='shot_clock_seconds_remaining',
            field=models.PositiveSmallIntegerField(default=24),
        ),
    ]
