# Generated by Django 5.2.16 on 2026-08-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_fixture_quarter_length_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='registration_form_url',
            field=models.URLField(blank=True, help_text='Google Form link for team/player registration — shown as a button on the tournament page.'),
        ),
    ]
