# Generated by Django 5.2.16 on 2026-08-07 15:17

import tournaments.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0008_fixture_individual_scoring_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixture",
            name="pool_name",
            field=models.CharField(
                blank=True,
                help_text="Pool label (A, B, C…) for pool-stage fixtures",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="fixture",
            name="stage",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name="tournament",
            name="fixture_mode",
            field=models.CharField(
                choices=[
                    ("CUSTOM", "Custom Fixtures"),
                    ("POOL", "Pool Stage + Knockout"),
                ],
                default="CUSTOM",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="pool_config",
            field=models.JSONField(
                blank=True, default=tournaments.constants.default_pool_config
            ),
        ),
    ]
