# Generated by Django 5.2.17 on 2026-08-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_fixture_pool_name_fixture_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembership',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Optional contact number', max_length=20),
        ),
    ]
