# Generated by Django 5.2.16 on 2026-07-11 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerapplication',
            name='sports',
            field=models.ManyToManyField(blank=True, related_name='organizer_applications', to='tournaments.sport'),
        ),
        migrations.AddField(
            model_name='organizerapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizers_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='sports',
            field=models.ManyToManyField(blank=True, related_name='interested_players', to='tournaments.sport'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
