# Generated by Django 5.2.16 on 2026-07-12 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
        (
            "tournaments",
            "0002_eventcategory_distance_km_highlight_duration_seconds_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="playerprofile",
            name="rating",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Skill rating (e.g. a chess Elo). Shown on rating-based standings.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="tournaments.tournament",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "tournament"),
                        name="uniq_user_tournament_follow",
                    )
                ],
            },
        ),
    ]
