# Generated by Django 5.2.16 on 2026-07-12 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tournaments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=160)),
                ("message", models.TextField(max_length=600)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("error", "Critical"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                (
                    "show_on_site",
                    models.BooleanField(
                        default=True,
                        help_text="Display as a banner on the public site.",
                    ),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=160)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video link"),
                            ("document", "Document"),
                        ],
                        default="image",
                        max_length=10,
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="library/")),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="Use for a YouTube or externally hosted asset.",
                    ),
                ),
                ("alt_text", models.CharField(blank=True, max_length=200)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "tournament",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_assets",
                        to="tournaments.tournament",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("summary", models.CharField(blank=True, max_length=300)),
                ("body", models.TextField()),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="news/"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sport",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="news",
                        to="tournaments.sport",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="news",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "news",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="TournamentSC", max_length=80)),
                (
                    "tagline",
                    models.CharField(default="Play. Compete. Conquer.", max_length=160),
                ),
                (
                    "support_email",
                    models.EmailField(
                        default="support@tournamentsc.app", max_length=254
                    ),
                ),
                ("contact_phone", models.CharField(blank=True, max_length=32)),
                (
                    "meta_description",
                    models.CharField(
                        default="The live home for local, multi-sport tournaments — discover, follow, and run them in one place.",
                        max_length=300,
                    ),
                ),
                (
                    "allow_player_registration",
                    models.BooleanField(
                        default=True, help_text="Turn off to close new player sign-ups."
                    ),
                ),
                (
                    "allow_organizer_registration",
                    models.BooleanField(
                        default=True,
                        help_text="Turn off to close new organizer sign-ups.",
                    ),
                ),
                (
                    "auto_approve_organizers",
                    models.BooleanField(
                        default=False,
                        help_text="Approve organizer applications without manual review.",
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Show a maintenance notice to the public site.",
                    ),
                ),
                (
                    "maintenance_message",
                    models.CharField(
                        blank=True,
                        default="TournamentSC is undergoing scheduled maintenance. Live scores may be delayed.",
                        max_length=300,
                    ),
                ),
                ("live_score_poll_seconds", models.PositiveIntegerField(default=12)),
                ("featured_limit", models.PositiveIntegerField(default=5)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "site settings",
                "verbose_name_plural": "site settings",
            },
        ),
    ]
