# Generated by Django 5.2.16 on 2026-08-03 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='maintenance_message',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='maintenance_mode',
        ),
    ]
